name: CI/CD Pipeline
on:
  push:
    branches: [master] # 只有 push 到 master 分支才触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 登录阿里云镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建并推送到阿里云
        run: |
          # 定义变量方便使用
          IMAGE_NAME=${{ secrets.DOCKER_REGISTRY }}/rch_dev/devops-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: 部署到服务器 (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 定义变量方便使用
            IMAGE_NAME=${{ secrets.DOCKER_REGISTRY }}/rch_dev/devops-app:latest
            docker pull $IMAGE_NAME
            docker stop devops-app || true
            docker rm -f devops-app || true
            docker run -d --name devops-app -p 80:80 $IMAGE_NAME
